openapi: "3.0.3"
info:
  title: "ipavorbereitung API"
  description: "ipavorbereitung API"
  version: "1.0.0"
servers:
  - url: "https://localhost:8080"
paths:
  /cities:
    get:
      summary: "GET cities"
      operationId: "getAll"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/City"
  /cities/{id}:
    get:
      summary: "GET cities/{id}"
      operationId: "getCityByID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/City"
components:
  schemas:
    City:
      type: "object"
      properties:
        name:
          type: "string"
        postalCode:
          type: "integer"
          format: "int32"
        id:
          type: "string"