openapi: "3.0.3"
info:
  title: "ipavorbereitung API"
  description: "ipavorbereitung API"
  version: "1.0.0"
servers:
  - url: "https://ipavorbereitung"
paths:
  /address-data:
    get:
      summary: "GET address-data"
      operationId: "getAll"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Addressdata"
  /address-data/{id}:
    get:
      summary: "GET address-data/{id}"
      operationId: "getAddressDataById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Addressdata"
components:
  schemas:
    City:
      type: "object"
      properties:
        name:
          type: "string"
        postalCode:
          type: "integer"
          format: "int32"
        id:
          type: "string"
    Addressdata:
      type: "object"
      properties:
        streetName:
          type: "string"
        streetNumber:
          type: "string"
        city:
          $ref: "#/components/schemas/City"
        id:
          type: "string"